{{- if and .Values.enabled (not .Values.ipam.passSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: akc-ipam-device-secret
  namespace: {{.Values.global.namespace }}
data:
  u: {{ .Values.ipam.user | b64enc  }}
  p: {{ .Values.ipam.pass | b64enc }}
{{- end }}
