{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    {{- include "lcs.labels" . | nindent 4 }}
    app.kubernetes.io/name: db
    app.kubernetes.io/component: database
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: database
    spec:
      securityContext:
        {{- include "lcs.podSecurityContext" 26 | nindent 8 }}
        fsGroup: 26
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- include "lcs.containerSecurityContext" 26 | nindent 12 }}
          ports:
            - containerPort: 5432
              name: tcp-postgresql
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.db.role | quote }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetSecretName }}
                  key: DB_PASSWORD
                  optional: true
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetSecretName }}
                  key: DB_NAME
                  optional: true
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.targetSecretName }}
                  key: DB_PASSWORD
                  optional: true
            - name: POSTGRESQL_LOG_DESTINATION
              value: /dev/stderr
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data
      {{- if not .Values.db.persistence.enabled }}
      volumes:
        - name: pgdata
          emptyDir: {}
      {{- end }}
  {{- if .Values.db.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.db.storage.storageClassName }}
        storageClassName: {{ .Values.db.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.db.storage.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "lcs.labels" . | nindent 4 }}
    app.kubernetes.io/name: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
