{{- if not .Values.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalSecret.targetSecretName }}
  labels:
    {{- include "lcs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
