apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesense.fullname" . }}
  labels:
    {{- include "kubesense.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  TESTS_STORE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  TRACES_STORE_PASSWORD: {{ .Values.secrets.tracesStorePassword | quote }}
  ALERTMANAGER_PASSWORD: {{ .Values.secrets.alertmanagerPassword | quote }}
  ALERTMANAGER_SMTP_AUTH_PASSWORD: {{ .Values.secrets.smtpAuthPassword | quote }}
