{{- $service := .Values.secret }}
{{ if  .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretname }}
  namespace: {{.Values.global.namespace }}
data:
  tls.crt: {{ .Values.secret.crt }}
  tls.key: {{ .Values.secret.key }}
{{- end }}
---
{{ if  .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grpc_secret.secretname }}
  namespace: {{.Values.global.namespace }}
data:
  grpc-tls.crt: {{ .Values.grpc_secret.crt }}
  grpc-tls.key: {{ .Values.grpc_secret.key }}
  grpc-ca.cert: {{ .Values.grpc_secret.ca }}
{{- end }}
---
{{- if and .Values.enabled .Values.global.debug_secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.debug_secret.secretname }}
  namespace: {{.Values.global.namespace }}
data:
  tls.crt: {{ .Values.global.debug_secret.crt }}
  tls.key: {{ .Values.global.debug_secret.key }}
{{- end }}