apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test-connection"
  annotations:
    "helm.sh/hook": test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: registry.access.redhat.com/ubi10/ubi-minimal:latest
      command: ["sh","-c","echo ok"]