apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.16.0
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:3608008094182193695
        chart-uri: N/A
        digests:
            chart: sha256:057419a86f96918a2fa5d5177269aca050e15cfeb8c1e7f60f94582cd568bff7
            package: 54b97c869370154c736bbd80cda89870c0666388d160308c228977ac23be3897
        lastCertifiedTimestamp: "2026-08-25T10:36:07.236229-05:00"
        testedOpenShiftVersion: "4.20"
        supportedOpenShiftVersions: '>=4.8'
        webCatalogOnly: true
    chart:
        name: 5g-smf-global
        home: ""
        sources: []
        version: 1.260814.10982825
        description: A Helm chart for 5G Core cSMF(26/08/14)
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 26.B.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: 5g-smf-gmc-26b
            charts.openshift.io/provider: Samsung Electronics
            charts.openshift.io/releaseDate: 26/08/14
            charts.openshift.io/supportURL: https://www.samsung.com/global/business/networks/contact-us/
        kubeversion: '>= 1.21.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/has-notes
      type: Optional
      outcome: FAIL
      reason: Chart does not contain NOTES.txt
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ndns:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ima:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ncdh:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ndia:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-vpbt:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-bfdm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-lem:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-fm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-dm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-pm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-vcdm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-fqm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-smps:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-cap:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-ui:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-dbcs:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-crtm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-nfmc:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ldbm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-eves:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ngtp:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-nrad:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-crm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-clbc:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-nsm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-nipm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-upic:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-putc:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-utilbox:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-imim:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-smf-ofcm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-ncth:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-inpx:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-imcm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-clm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-bgpm:SVR26B_20260814_10982825
        Image is not Red Hat certified : quay.samsung.bos2.lab/samsung_5gc/integ-core/global-nf-dbcb:SVR26B_20260814_10982825
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
