{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rest_secret.secretname }}
  namespace: {{.Values.global.namespace }}
data:
  rest-tls.crt: {{ .Values.rest_secret.crt }}
  rest-tls.key: {{ .Values.rest_secret.key }}
  rest-ca.cert: {{ .Values.rest_secret.ca }}
---
{{- if not .Values.alteon.adcSecretCredential }}
apiVersion: v1
kind: Secret
metadata:
  name: akc-alteon-device-secret
  namespace: {{.Values.global.namespace }}
data:
  u: {{ .Values.alteon.user | b64enc  }}
  p: {{ .Values.alteon.pass | b64enc }}
{{- end }}  
{{- end }}
