name: Install our CI scripts
description: |
  Handles installation and caching/restore of the CI scripts in a virtualenv.
inputs:
  working-directory:
    description: Basedir in which to save / restore cache and install venv.
    default: './'
    required: false
  python-version:
    description: Installed Python version
    required: true
runs:
  using: composite
  steps:
  - name: Setup venv
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      # set up python
      python3 -m venv ve1
      cd scripts
      ../ve1/bin/pip3 install -r requirements.txt
      ../ve1/bin/pip3 install .
