Feature: Report only submission
    Partners, redhat and community users can publish their chart by submitting
    error-free report that was generated by chart-verifier.

    Examples:
        | report_path               |
        | tests/data/report.yaml    |
    

    Scenario Outline: A partner or redhat associate submits an error-free report
        Given the vendor <vendor> has a valid identity as <vendor_type>
        And an error-free report is used in <report_path>
        When the user sends a pull request with the report
        Then the user sees the pull request is merged
        And the index.yaml file is updated with an entry for the submitted chart
    
        Examples:
            | vendor_type  | vendor    |
            | partners     | hashicorp |

    Scenario Outline: A community user submits an error-free report
        Given the vendor <vendor> has a valid identity as <vendor_type>
        And an error-free report is used in <report_path>
        When the user sends a pull request with the report
        Then the pull request is not merged
        And user gets the <message> in the pull request comment

        Examples:
            | vendor_type   | vendor    | message                                                                                     |
            | community     | redhat    | Community charts require maintainer review and approval, a review will be conducted shortly |
