Feature: Report only submission with provider control settings
  Partners can prevent publication of their chart by submitting
  error-free report that was generated by chart-verifier and with
  prvider controlled delivery set in the report and the OWNERS file.

  @external-feedback
  Scenario Outline: [HC-06-001] A partner associate submits an error-free report with provider controlled delivery
    Given the vendor "<vendor>" has a valid identity as "<vendor_type>"
    And provider delivery control is set to "<provider_control_owners>" in the OWNERS file
    And report is used in "<report_path>"
    When the user sends a pull request with the report
    Then the user sees the pull request is merged
    And the "<index_file>" is updated with an entry for the submitted chart

    @partners @smoke @full
    Examples:
      | vendor_type  | vendor    | report_path                             | index_file                        | provider_control_owners |
      | partners     | hashicorp | tests/data/HC-06/partner/report.yaml    | unpublished-certified-charts.yaml | true                    |

  @external-feedback 
  Scenario Outline: [HC-06-002] A partner associate submits an error-free report and chart with provider controlled delivery
    Given the vendor "<vendor>" has a valid identity as "<vendor_type>"
    And provider delivery control is set to "<provider_control_owners>" in the OWNERS file
    And an error-free chart tarball used in "<chart_path>" and report in "<report_path>"
    When the user sends a pull request with the report
    Then the pull request is not merged
    And user gets the "<message>" in the pull request comment

    @partners @full
    Examples:
      | vendor_type  | vendor    | chart_path                  | report_path                          | provider_control_owners | message                                                                                              |
      | partners     | hashicorp | tests/data/vault-0.17.0.tgz | tests/data/HC-06/partner/report.yaml | true                    | The web catalog distribution method requires the pull request to be report only. |

  @external-feedback
  Scenario Outline: [HC-06-003] A partner associate submits an error-free report with inconsistent provider controlled delivery setting
    Given the vendor "<vendor>" has a valid identity as "<vendor_type>"
    And provider delivery control is set to "<provider_control_owners>" in the OWNERS file
    And report is used in "<report_path>"
    When the user sends a pull request with the report
    Then the pull request is not merged
    And user gets the "<message>" in the pull request comment

    @partners @full
    Examples:
      | vendor_type  | vendor    | report_path                            | provider_control_owners | message                                                                 |
      | partners     | hashicorp | tests/data/common/partner/report.yaml  | true                    | The web catalog distribution method is set for the chart but is not set in the report. |
      | partners     | hashicorp | tests/data/HC-06/partner/report.yaml   | false                   | Report indicates web catalog only but the distribution method set for the chart is not web catalog only. |
