apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.15.0
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:18246075952692521338
        chart-uri: /charts/dify-enterprise-3.9.6.tgz
        digests:
            chart: sha256:34a7f9105f432a982613c2e4a14807f84e978479b89f36392d0958662e5fb65b
            package: c9d8f0a4fecff5eb70bfb3d264c362e3dabe5a06704dc7b1621d8c2c3bb7dd85
        lastCertifiedTimestamp: "2026-07-15T02:01:33.719229+00:00"
        testedOpenShiftVersion: "4.21"
        supportedOpenShiftVersions: '>=4.8'
        webCatalogOnly: false
    chart:
        name: dify-enterprise
        home: https://dify.ai
        sources:
            - https://github.com/langgenius/dify
            - https://github.com/langgenius/dify-helm
        version: 3.9.6
        description: Release https://langgenius.github.io/dify-helm/
        keywords:
            - dify
            - langgenius
            - llm
        maintainers:
            - name: Yeuoly
              email: yeuoly@dify.ai
              url: ""
            - name: takatost
              email: takatost@dify.ai
              url: ""
        icon: https://avatars.githubusercontent.com/u/127165244
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.13.3
        deprecated: false
        annotations:
            charts.openshift.io/name: Dify Enterprise
        kubeversion: '>=1.21.0'
        dependencies:
            - name: postgresql
              version: 12.5.6
              repository: https://charts.bitnami.com/bitnami
              condition: postgresql.enabled
              tags:
                - postgres
            - name: redis
              version: 16.13.2
              repository: https://charts.bitnami.com/bitnami
              condition: redis.enabled
              tags:
                - redis
            - name: weaviate
              version: 16.1.0
              repository: https://weaviate.github.io/weaviate-helm
              condition: weaviate.enabled
              tags:
                - vector
                - search
            - name: qdrant
              version: 0.8.5
              repository: https://qdrant.github.io/qdrant-helm
              condition: qdrant.enabled
              tags:
                - vector
                - search
        type: application
    chart-overrides: ""
results:
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image is Red Hat certified : langgenius/dify-ee-enterprise-frontend:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-plugin-connector:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-plugin-daemon-serverless:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-plugin-manager:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-web:3.9.6-ubi9
        Image is Red Hat certified : registry.access.redhat.com/ubi9/ubi-minimal:latest
        Image is Red Hat certified : langgenius/dify-ee-gateway:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-sandbox:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-api:3.9.6-ubi9
        Image is Red Hat certified : langgenius/dify-ee-enterprise:3.9.6-ubi9

