# -*- coding: utf-8 -*-
"""Report only submission

Partners, redhat and community users can publish their chart by submitting
error-free report that was generated by chart-verifier.
"""
import pytest
from pytest_bdd import scenario

from functional.utils.chart_certification import ChartCertificationE2ETestSingle

@pytest.fixture
def workflow_test():
    test_name = 'Test Chart Report Only'
    workflow_test = ChartCertificationE2ETestSingle(test_name=test_name)
    yield workflow_test
    workflow_test.cleanup()


@scenario('../features/HC-16_dash_in_version.feature', "[HC-16-001] A partner or redhat associate submits report only with dash in chart version")
def test_partner_or_redhat_user_submits_report_dash_in_version():
    """A community user submits an error-free report"""
