# -*- coding: utf-8 -*-
"""Report only submission

Partners, redhat and community users can publish their chart by submitting
error-free report that was generated by chart-verifier.
"""
import pytest
from pytest_bdd import scenario

from functional.utils.chart_certification import ChartCertificationE2ETestSingle

@pytest.fixture
def workflow_test():
    test_name = 'Test Chart Report Only'
    test_report = 'tests/data/report.yaml'
    workflow_test = ChartCertificationE2ETestSingle(test_name=test_name, test_report=test_report)
    yield workflow_test
    workflow_test.cleanup()


@scenario('../features/report_without_chart.feature', "A partner or redhat associate submits an error-free report")
def test_partner_or_redhat_user_submits_report():
    """A partner or redhat associate submits an error-free report."""

@scenario('../features/report_without_chart.feature', "A community user submits an error-free report")
def test_community_user_submits_report():
    """A community user submits an error-free report"""
